# Generated by Django 5.2.5 on 2026-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
