# Generated by Django 5.2.5 on 2025-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
