# Generated by Django 5.2.5 on 2025-10-25 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_remove_sponsorprofile_address_sponsorprofile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorprofile',
            old_name='organization_name',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
