# Generated by Django 5.2.5 on 2025-10-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_rename_organization_name_sponsorprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_id',
            field=models.CharField(blank=True, help_text='Internal or Stripe-linked Sponsor ID', max_length=100, null=True, unique=True),
        ),
    ]
