# Generated by Django 5.2.5 on 2025-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=120)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('story', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children_photos/')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
