# Generated by Django 5.2.5 on 2025-08-22 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('sponsor', '0002_remove_sponsorprofile_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sponsor.sponsorprofile'),
        ),
    ]
