# Generated by Django 5.2.5 on 2025-10-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='ChildProfile',
        ),
    ]
