# Generated by Django 5.2.5 on 2025-10-25 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_rename_child_childprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
