# Generated by Django 5.2.5 on 2025-10-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_remove_childprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='guardian_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
