# Generated by Django 5.2.5 on 2025-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_childprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='children/photos/'),
        ),
    ]
