# Generated by Django 5.2.5 on 2025-11-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_childprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='photo',
            field=models.ImageField(blank=True, default='children/photos/default.jpg', null=True, upload_to='children/photos/'),
        ),
    ]
