# Generated by Django 5.2.5 on 2025-10-26 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='stripe_session_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
