# Generated by Django 5.2.5 on 2025-08-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_child_alter_sponsor_user_delete_child'),
        ('sponsor', '0002_remove_sponsorprofile_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='sponsor.sponsorprofile'),
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
