# Generated by Django 5.2.5 on 2025-11-01 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_date_donation_created_at_and_more'),
        ('sponsors', '0004_sponsorprofile_sponsor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='sponsors.sponsorprofile'),
        ),
    ]
