# Generated by Django 5.2.5 on 2025-11-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_sponsor'),
        ('sponsors', '0004_sponsorprofile_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsorprofile'),
        ),
    ]
